### ISSUE TITLE
Can't boot while maintenance 

### ISSUE THREAD

**Issue by Lupetta** [That-Guy-Jack/HP-ILO-Fan-Control#17]
Hello when i switched the switch s6 in ON Position i'm not able to boot the OS installed on the hard drives
![ilo 1](https://user-images.githubusercontent.com/70319270/169714720-53652724-9305-4665-bf11-0feaaa7f7adf.PNG)

**Comment by That-Guy-Jack** [comment]
hm, never seen that before, does  pre initialisation complete fine (bios,, raid controllers etc)? 

+ any info on what server your using will be helpful 👍

**Comment by Lupetta** [comment]
Hello,
i'm using dl360p g8 with p420i raider control

 does pre initialisation complete fine (bios,, raid controllers etc)?
 not really it will take like half of the time but without erros

**Comment by Lupetta** [comment]
Hello i think i got it, i flashed the firmware but now i have these 2 errors: 
![image](https://user-images.githubusercontent.com/70319270/169717169-a7af6390-0ed5-4003-bc85-f4e17a69c9c8.png)
![image](https://user-images.githubusercontent.com/70319270/169717182-b8459db5-8cb6-4817-be4a-e9c8acbe9fad.png)

**Comment by That-Guy-Jack** [comment]
Form a quick google search you need to enable  the key exchange for the ILO ssh 

```
#Legacy changes
KexAlgorithms +diffie-hellman-group1-sha1
Ciphers +aes128-cbc
```
From [unix.stackexchange.com](https://unix.stackexchange.com/questions/340844/how-to-enable-diffie-hellman-group1-sha1-key-exchange-on-debian-8-0) 


As for the other error i'm not to sure. do you have any extra PCIE devices in your server?

**Comment by Lupetta** [comment]
Hello,
i added to ~/.ssh/config. 
Host MYILOIP
    KexAlgorithms +diffie-hellman-group1-sha1
and also tried with 
#Legacy changes
KexAlgorithms +diffie-hellman-group1-sha1
Ciphers +aes128-cbc
but now i have this error:
![image](https://user-images.githubusercontent.com/70319270/169717760-5ea9f979-41df-4da3-a922-c853592ecfce.png)


Yes i have another PCIE device that's an nvme adpater that's working fine since i see the disk on proxmox 
i also have a 4gbit ethenet ports that's working fine

i dont know why due the error permission denied now the fans are on 7% is it working?
now i'm worrying more about the error of pcie device how can i fix it?

**Comment by Lupetta** [comment]
Hello,
oh i just rebooted right now and
![image](https://user-images.githubusercontent.com/70319270/169718109-b27a3fa1-de80-4da6-80bd-3c09a396241b.png)
seems it fixed itself haha
what about the permission denied?

**Comment by Lupetta** [comment]
Hello,
i'm so stupid, i putted the username on the password field, now it's everything working thank you and sorry for the disturb!

**Comment by Lupetta** [comment]
About 
I recommend especially for the DL360 to add a small 40mm fan to the RAID controller to keep it cool.
> becuase it's getting now 90-100C° do you suggest me any fan that i can install on it? or if you have some examples that i can follow?

Thank you

**Comment by That-Guy-Jack** [comment]
> About I recommend especially for the DL360 to add a small 40mm fan to the RAID controller to keep it cool.
> 
> > becuase it's getting now 90-100C° do you suggest me any fan that i can install on it? or if you have some examples that i can follow?
> 
> Thank you

Its just a small fan to keep airflow over the Raid controller if you want something off the shelf something like this [](https://www.amazon.co.uk/ELUTENG-Ventilator-Computer-Compatible-Raspberry/dp/B07F1NV9T7?th=1) would work well 

If your a bit more DIY a cheap 5v 40mm fan and a old USB cable can also be made to work.

in my case i ended up just putting the 40mm fan just ontop of the heatsink and its stayed in place pretty well

**Comment by Lupetta** [comment]
oh i'll take for sure one 40mm i was looking for the noctua one or also the buy the one that you sent to me, anyway just a quick question, how did you manage to connect it on the motherboard? like did you just used an usb cable and connected on the back of the server or did you use some pins on the motherboard?

Thank you

**Comment by That-Guy-Jack** [comment]
I ended up using the internal USB header near the power supply section of the motherboard (next to the SD card Slot)

**Comment by Lupetta** [comment]
Thank you for all everything is working super fine!
