### ISSUE TITLE
Ideas/Request - How to apply this to ESXi itself?

### ISSUE THREAD

**Issue by dperez-sct** [That-Guy-Jack/HP-ILO-Fan-Control#3]
Hi! My g8 it's a ESXi environment and I have 2 ways to implement this.
- Make a ubuntu VM and install script on it.
- In any way, install this on ESXi.

There are any way already explored to make it work on ESXi?

Thanks a lot!

**Comment by supajason** [comment]
I ran Ubuntu live via USB to install (up to step 4)
I'm having issues trying to ssh to ilo from esxi

**Comment by That-Guy-Jack** [comment]
Hm I'm not sure how to run this on esxi as I run proxmox normally. I'll spin up a esxi VM and try it out later I'll let you know how it goes

**Comment by That-Guy-Jack** [comment]
Still not got any major updates atm, but with the limited research the ESSXI console doesn't seem to support the sensor collection that i have set up, ill keep you updated on what i can find,

**Comment by That-Guy-Jack** [comment]
Hi it seems without full access to a essxi machine i can't create a functioning script, if any of you guys want to write a script for essxi feel free and ill add it to this repo

**Comment by supajason** [comment]
It seems you can't directly SSH into the ILO shared port from ESXI - workaround is to use the dedicated port and plug that into the network....

**Comment by That-Guy-Jack** [comment]
Interesting, recently upgrade to a DL380 (the 2u g8) so I'll be able to test with my dl360 with essxi now

**Comment by That-Guy-Jack** [comment]
no, sadly but i may be implementing a second set of scripts specifically for running on exsi (e.g using ilo temps)

**Comment by divadiow** [comment]
ooh yes please

**Comment by moni11811** [comment]
Hmm, [try this](https://github.com/moni11811/Ilo2.73/blob/main/Autofan.sh)

**Comment by thomaswilbur** [comment]
I'm working on a version currently, let you know on release @dperez-sct 
https://github.com/thomaswilbur/HP-ILO-Fan-Control
Currently manual no automation but the script does run.
