### ISSUE TITLE
sshpass not working

### ISSUE THREAD

**Issue by ErgoProxy1337** [That-Guy-Jack/HP-ILO-Fan-Control#6]
Hi there. Sadly the sshpass is not working for me on proxmox. Any idea?

I even executed it manually like 
`sshpass -p myIloPw ssh myIloUsr@MyIloIp 'fan p 3 max 255'`
but seams not to work. Only when I connect over ssh directly and use the `fan p 3 max 255` it works.

**Comment by That-Guy-Jack** [comment]
Hi, do you get any error when running the command ?

also setting your fan p 3 max 255 is the equivalent of setting the fan to max speed 

Try running this and see if it makes a difference 
`sshpass -p myIloPw ssh myIloUsr@MyIloIp 'fan p 3 max 30'`

Jack

**Comment by ErgoProxy1337** [comment]
Hi.
No, no error here. It just takes like 2 secs until I can type again and thats it. Seams like he would rly do something but no full speed fans to hear there...

And yes, I know about 255 = max :) its just for testing purposes. 
As I said, 
ssh ilouser@iloip & ilopw then fan p 3 max 255 works for me and the fans starts to spin at full speed.
Seams only like sshpass isnt working... mhm

**Comment by That-Guy-Jack** [comment]
Hi, running the SSH pass command doesn't output anything to the console when you run it, the fans will only ramp to 100% if the default fan control requires it, and did you try changing 255 to a lower number (20-30) and checking the fan speed on the ILO to see if it does any thing. 

Let me know what happens as the script works fine on both of my hp servers (dl380p g8 and dl360p g8)

Jack

**Comment by ErgoProxy1337** [comment]
Yes, ofc I tried all this before I wrote here :)
![fan1](https://user-images.githubusercontent.com/38110913/126890876-d5ca6c44-2c67-4696-b682-e6f1324bf8c5.jpg)
![fan2](https://user-images.githubusercontent.com/38110913/126890880-7a0d521b-870c-4685-8320-72fb50eabfec.jpg)
![fan3](https://user-images.githubusercontent.com/38110913/126890881-bcbd665f-32cd-4fdc-a3cb-b8346b1d1a7b.jpg)
![fan4](https://user-images.githubusercontent.com/38110913/126890882-d4e4dc0c-9c57-4a4a-b624-4bdcfe346e1b.jpg)

As u can see.. unchanged trough sshpass

**Comment by ErgoProxy1337** [comment]
> 
> 
> Sorry For the late responce ive just been settin up a new Server with the fan script and noted that the fans only seem to be controled by the script when run via the service

Hi and np. 
What do u exactly mean?

**Comment by That-Guy-Jack** [comment]
Sorry for the confusion when i ran it without the service i forgot to do `chmod +x autofan.sh` meaning the script didn't run correctly, 
Ill make a Custom version of the script with log points to see if the script is running properly, 

Also can you grab the latest version of the fan scripts as removing the double brackets stops the script from working)
