### ISSUE TITLE
How to validate fans

### ISSUE THREAD

**Issue by softwareuser99** [That-Guy-Jack/HP-ILO-Fan-Control#7]
Hi there, thanks for this amazing piece of software! I use a G9 and it seems to work fine. However I do have a question which may seem dumb, however I just want to check I get this right:

- below if Tx > xx refers to temperature in Celsius, right? per the sensor reading the core temp, right?
- is the scale used the same as the 0-255 from the fan info? 
- how does this affect the 6 fans in the server, does it ramp them all up equally (left side, right side?)

Sorry, just getting started with this whole fan control piece. I assume the fan groupings being 0-5 are represented below with the 0-1-2 and 3-4-5.

Appreciate just a little bit more clarity! Cheers!

PS: I edited the below MAX to 160 to avoid the fans going off on full blast..

`echo "==============="
echo "CPU 2 Temp $T2 C"
echo "==============="

if [[ $T2 > 67 ]]
   then
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 0 max 160'
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 1 max 160'
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 2 max 160'

elif [[ $T2 > 58 ]]
    then
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 0 max 39'
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 1 max 39'
        sshpass -p $PASSWORD ssh $USERNAME@$ILOIP 'fan p 2 max 39'
elif [[ $T2 > 54 ]]
    then
`

**Comment by That-Guy-Jack** [comment]
Hi, the $T2 > xx is the cpu temp in C of each CPU, (T1 is cpu 1 T2 is CPU 2) Based off of the CPU temp in each half of the server depends on the speed of the fans (e.g if cpu 2 is under load the 3 fans (Fans 0 1 and 2) next to CPU 2 will Ramp up to combat the extra heat) 

The fans are counted from 0 - 5 with 0 in the script  being Fan 1 in the ILO and in the chassis itself 

Feel free to ask more questions if i made no sense there lol

**Comment by softwareuser99** [comment]
Thanks, that all makes sense. I am however getting a reading on zone 0 and zone 1 going up to 78 degrees C. I’ll need to tweak the fan levels I guess as I could imagine those zones being areas like the psu or pci slot bays…

Would it make sense to include these other thermal sensors as well in the evaluation to ramp up the fans?

thanks again, appreciate the patience!

**Comment by softwareuser99** [comment]
Turns out the issue was the SSH connection as the script didn't output any errors that it wasn't able to connect (again the issue with the old encryption algo. Once I added the exception to the ssh server config, everything worked like a charm!
